### PR TITLE
MOB-120 Migrate all plugins to AndroidX

### PR DESCRIPTION
**Pull request by LcTwisk**
With the changes in https://github.com/PicnicSupermarket/electrode-native-private/pull/18, all new plugins will automatically be AndroidX compatible.

### CODE REVIEW

**Review by FlorBosch — APPROVED** [review]
Approved but I believe we'll have to wait for the changes in the other repositories to be merged before we can merge this one.

**Comment by LcTwisk** [comment]
> Approved but I believe we'll have to wait for the changes in the other repositories to be merged before we can merge this one.

Funny enough, the Android container build seems to succeed without changes in other repositories 🤔

**Comment by FlorBosch** [comment]
> Funny enough, the Android container build seems to succeed without changes in other repositories 🤔

Could it be because of the `postinstall` step you've added?

**Comment by LcTwisk** [comment]
I don't think so, `jettifier` transforms non-AndroidX to AndroidX, not the other way around. 
Will test again, but probably it's safer to wait for the other changes to be ready anyway 👍

**Pull request merged**
